test_that("*_numeric() | general test", {
  test_numeric(x = as.integer(1)) |> expect_true()
  test_numeric(x = as.double(1)) |> expect_true()
  test_numeric(x = as.numeric(1)) |> expect_true()
  test_numeric(x = c(1, NA), any_missing = TRUE) |> expect_true()
  test_numeric(x = NULL, null_ok = TRUE) |> expect_true()
  test_numeric(x = lubridate::dhours()) |> expect_false()
  test_numeric(x = letters) |> expect_false()
  test_numeric(x = datasets::iris) |> expect_false()
  test_numeric(x = c(1, NA), any_missing = FALSE) |> expect_false()
  test_numeric(x = NULL, null_ok = FALSE) |> expect_false()
  test_numeric(x = 1, lower = 2) |> expect_false()
  test_numeric(x = 1, upper = 0) |> expect_false()

  check_numeric(x = c(1, NA), any_missing = FALSE) |> checkmate::expect_string()
  check_numeric(x = NULL, null_ok = FALSE) |> checkmate::expect_string()
  check_numeric(x = 1, lower = 2) |> checkmate::expect_string()
  check_numeric(x = 1, upper = 0) |> checkmate::expect_string()
  check_numeric(x = c("a", "b")) |> checkmate::expect_string()

  assert_numeric(x = c(1, 1)) |> expect_equal(c(1, 1))
  assert_numeric( x = c("a", "b")) |> testthat::expect_error()
})
